version: "3.7"

services:
  db:
    platform: linux/amd64
    container_name: postgres_paper
    image: postgres:14
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - paper-volumes:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - paper-networks

  marp-presentation:
    platform: linux/amd64
    container_name: marp-presentation
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true
    env_file:
      - "./config/.env"
    ports:
      - "5011:5000"
    volumes:
      - ".:/workspace"
    environment:
      - PORT=5000
      - DEBUG=true
    depends_on:
      - db
    networks:
      - paper-networks

networks:
  paper-networks:
    driver: bridge

volumes:
  paper-volumes:
